/** 全部可用图标名，按原版 demos 的 icons 页分组与顺序（共 293 个） */
export interface IconGroup {
  /** 原版分组名（如 `movement`、`editing-core`），即页面上 `Icons – <name>` 的 `<name>` */
  name: string;

  /** 该组的图标名，可直接传给 `Icon` 的 `icon` */
  icons: string[];
}

/** 全部图标分组 */
export const ICON_GROUPS: IconGroup[] = [
  {
    name: "movement",
    icons: [
      "arrowDown",
      "arrowNext",
      "arrowPrevious",
      "arrowUp",
      "collapse",
      "downTriangle",
      "draggable",
      "draggableHorizontal",
      "draggableVertical",
      "draggableXY",
      "doubleChevronEnd",
      "doubleChevronStart",
      "expand",
      "move",
      "first",
      "last",
      "next",
      "previous",
      "sortVertical",
      "upTriangle",
    ],
  },
  {
    name: "content",
    icons: [
      "article",
      "articles",
      "articleAdd",
      "articleCheck",
      "articleDisambiguation",
      "articleNotFound",
      "articleSearch",
      "articlesSearch",
      "articleRedirect",
      "asterisk",
      "database",
      "die",
      "download",
      "folderPlaceholder",
      "history",
      "info",
      "infoFilled",
      "merge",
      "qrCode",
      "robot",
      "share",
      "shareAndroid",
      "shareIOS",
      "specialPages",
      "tabs",
      "tag",
      "update",
      "upload",
      "window",
    ],
  },
  {
    name: "alerts",
    icons: [
      "alert",
      "bell",
      "bellOutline",
      "error",
      "levelNone",
      "levelOne",
      "levelTwo",
      "levelThree",
      "live",
      "message",
      "notice",
      "speechBubble",
      "speechBubbleAlert",
      "speechBubbleAdd",
      "speechBubbles",
      "success",
      "tray",
    ],
  },
  {
    name: "interactions",
    icons: [
      "add",
      "browser",
      "cancel",
      "check",
      "checkAll",
      "clear",
      "clock",
      "close",
      "configure",
      "ellipsis",
      "verticalEllipsis",
      "feedback",
      "filter",
      "funnel",
      "funnelMatch",
      "hand",
      "heart",
      "heartOutline",
      "help",
      "helpNotice",
      "helpNoticeFilled",
      "home",
      "key",
      "keyboard",
      "lightbulb",
      "lightbulbOutline",
      "lightbulbDashed",
      "logIn",
      "logOut",
      "magicWand",
      "network",
      "networkOff",
      "newWindow",
      "pageSettings",
      "power",
      "printer",
      "reload",
      "restart",
      "rotate",
      "search",
      "settings",
      "subtract",
    ],
  },
  {
    name: "moderation",
    icons: [
      "bookmarkOutline",
      "bookmark",
      "block",
      "blockOutline",
      "unBlock",
      "flag",
      "unFlag",
      "lock",
      "unLock",
      "restore",
      "star",
      "halfStar",
      "unStar",
      "trash",
      "pushPin",
      "ongoingConversation",
      "suggestedInvestigations",
    ],
  },
  {
    name: "editing-core",
    icons: [
      "edit",
      "editLock",
      "editUndo",
      "link",
      "unLink",
      "linkExternal",
      "linkSecure",
      "redo",
      "undo",
    ],
  },
  {
    name: "editing-styling",
    icons: [
      "bigger",
      "smaller",
      "subscript",
      "superscript",
      "bold",
      "highlight",
      "italic",
      "strikethrough",
      "underline",
      "textLanguage",
      "textDirLTR",
      "textDirRTL",
      "textStyle",
    ],
  },
  {
    name: "editing-functions",
    icons: ["function", "functionArgument", "instance", "literal"],
  },
  {
    name: "editing-list",
    icons: ["indent", "listBullet", "listNumbered", "outdent"],
  },
  {
    name: "editing-advanced",
    icons: [
      "alignCenter",
      "alignLeft",
      "alignRight",
      "attachment",
      "calendar",
      "code",
      "copy",
      "cut",
      "diffs",
      "hieroglyph",
      "imageLayoutBasic",
      "imageLayoutFrame",
      "imageLayoutFrameless",
      "imageLayoutThumbnail",
      "labFlask",
      "language",
      "layout",
      "markup",
      "mathematics",
      "mathematicsDisplayBlock",
      "mathematicsDisplayDefault",
      "mathematicsDisplayInline",
      "newline",
      "noWikiText",
      "ocr",
      "outline",
      "palette",
      "paste",
      "puzzle",
      "quotes",
      "sandbox",
      "searchCaseSensitive",
      "searchDiacritics",
      "searchRegularExpression",
      "signature",
      "specialCharacter",
      "table",
      "tableAddColumnAfter",
      "tableAddColumnBefore",
      "tableAddRowAfter",
      "tableAddRowBefore",
      "tableCaption",
      "tableMergeCells",
      "tableMoveColumnAfter",
      "tableMoveColumnBefore",
      "tableMoveRowAfter",
      "tableMoveRowBefore",
      "templateAdd",
      "translation",
      "wikiText",
    ],
  },
  {
    name: "editing-citation",
    icons: [
      "book",
      "journal",
      "newspaper",
      "reference",
      "referenceExisting",
      "references",
    ],
  },
  {
    name: "media",
    icons: [
      "camera",
      "chart",
      "chartBar",
      "chartLine",
      "chartPie",
      "chartScatter",
      "exitFullscreen",
      "fullScreen",
      "image",
      "imageAdd",
      "imageBroken",
      "imageLock",
      "imageGallery",
      "microphone",
      "musicalScore",
      "pause",
      "pictureInPicture",
      "play",
      "stop",
      "subtitle",
      "threeDimensional",
      "volumeDown",
      "volumeOff",
      "volumeUp",
      "zoomIn",
      "zoomOut",
    ],
  },
  {
    name: "location",
    icons: ["globe", "map", "mapPin", "mapPinAdd", "mapTrail"],
  },
  {
    name: "user",
    icons: [
      "bookmarkList",
      "userAdd",
      "userAnonymous",
      "userAvatar",
      "userAvatarOutline",
      "userBlocked",
      "userChat",
      "userContributions",
      "userGroup",
      "userMentor",
      "userPages",
      "userRights",
      "userTalk",
      "userTemporary",
      "userTemporaryLocation",
      "watchlist",
    ],
  },
  {
    name: "layout",
    icons: [
      "menu",
      "recentChanges",
      "textFlow",
      "textSummary",
      "viewCompact",
      "viewDetails",
    ],
  },
  {
    name: "accessibility",
    icons: [
      "appearance",
      "bright",
      "halfBright",
      "notBright",
      "eye",
      "eyeClosed",
      "moon",
      "largerText",
      "smallerText",
      "universalDesign",
      "visionSimulator",
    ],
  },
  {
    name: "wikimedia",
    icons: [
      "logoCC",
      "logoCodex",
      "logoMediaWiki",
      "logoMetaWiki",
      "logoWikibooks",
      "logoWikidata",
      "logoWikifunctions",
      "logoWikimedia",
      "logoWikimediaCommons",
      "logoWikimediaDiscovery",
      "logoWikinews",
      "logoWikipedia",
      "logoWikiquote",
      "logoWikisource",
      "logoWikispecies",
      "logoWikiversity",
      "logoWikivoyage",
      "logoWiktionary",
    ],
  },
];
