version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
    ignore:
      # 大版本一律不自动更新，升级由人工评审进行
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      # 对照开发基线，手动控制版本
      - dependency-name: "oojs"
      - dependency-name: "jquery"
      - dependency-name: "@wikimedia/codex-design-tokens"
